import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "@components/common/footer";
import Shortcut from "./feature/shortcut/shortcut";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[#FFFCED] min-h-screen flex flex-col`}>
          <main className="flex-grow">
              {children}
          </main>

          <footer className="w-full">
              <Footer/>
          </footer>

          <Shortcut />
        </body>
    </html>
  );
}

